### PR TITLE
Fix typo and return PropertyNode. Fix #29.

### LINKED ISSUE #29: DevExpress  Satellite assembly Not included ！
dev

### PR DESCRIPTION
**Pull request by Leogiciel**

### CODE REVIEW

**Comment by tom-englert** [comment]
Please change your settings for the line endings to "checkout as is, commit as is" (core.autocrlf = false), I always get complaints from VS that the line endings are inconsistent.

**Comment by tom-englert** [comment]
Maybe it would be a good idea to change properties likde ```public IEnumerable<string> CustomActionRefs``` in to a method ```EnumerateCustomActionRefs()``` to clearly distinguish them from properties that return a collection.

**Comment by Leogiciel** [comment]
Done. I tried to apply [this procedure](https://help.github.com/articles/dealing-with-line-endings/) after having set autocrlf to false, but no changes to commit.

**Comment by Leogiciel** [comment]
Fix for #29 included

**Pull request closed without merging**
