### PR TITLE
Add custom action references and return PropertyNode created

### PR DESCRIPTION
**Pull request by Leogiciel**
Rebased on master branch to avoid useless merge

### CODE REVIEW

**Comment by Leogiciel** [comment]
Extensions installed, but it compiled again... However, I understood my typo... Sorry about that... 

Can you provide me a link for the extension you use ?

**Comment by tom-englert** [comment]
Best is to use the latest build from here:
https://ci.appveyor.com/project/SergeyTeplyakov/codecontracts/build/artifacts

The *helper.vsix is optional.

**Comment by Leogiciel** [comment]
Thank you !

Now it's only compiling if my Contract is well declared, you can merge the PR

**Comment by tom-englert** [comment]
Good job - can you share the code that's using this, maybe it can be integrated in Wax?

**Comment by Leogiciel** [comment]
You're welcome !

How do you want me to proceed : I include my project in the solution then PR you, or I share it in another repo ?

**Comment by tom-englert** [comment]
Just put it into a branch and tell me the branch name for a sneak preview.

Also I saw you had a french translation, but reverted the check in. Wouldn't that be another cool feature?

**Comment by Leogiciel** [comment]
OK for the branch, I will refactor things tonight or tomorrow because I made a "my company specific  tool", and I need to expose manufacturer property. For french language, don't worry, it's in my todo list. Best regards Tom, Brice Andreota Le 20 janv. 2017 20:08, tom-englert <notifications@github.com> a écrit :Just put it into a branch and tell me the branch name for a sneak preview.
Also I saw you had a french translation, but reverted the check in. Wouldn't that be another cool feature?

**Comment by Leogiciel** [comment]
I published my tool in my [RememberPropertiesEditor](https://github.com/Leogiciel/Wax/tree/RememberPropertiesEditor) branch.

**Pull request merged**
